### ISSUE TITLE
Master does not compile with 0.16.0

### ISSUE THREAD

**Issue by pavildon** [tree-sitter/zig-tree-sitter#43]
It seem that this depends on tree-sitter-c which depends on a version of tree-sitter that does not compile with zig 0.16.0.

Its the same error that the CI has: [CI log](https://github.com/tree-sitter/zig-tree-sitter/actions/runs/24640286719/job/72042913398#step:6:21)

```sh
~/zig-tree-sitter/ > nix develop . -c zig build
zig-pkg/tree_sitter-0.25.0-8heIf4xwAQCcM_rEJFSvWcc0Y6TaXQPw1kFZRWoea4Ne/build.zig:23:8: error: no field or member function named 'linkLibrary' in 'Build.Step.Compile'
    lib.linkLibrary(core.artifact("tree-sitter"));
    ~~~^~~~~~~~~~~~
/nix/store/9zyky24fffkbhnkmjcnrjcl3dmvx6w9x-zig-0.16.0/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const Compile = @This();
^~~~~
zig-pkg/tree_sitter-0.25.0-8heIf4xwAQCcM_rEJFSvWcc0Y6TaXQPw1kFZRWoea4Ne/build.zig:23:8: note: method invocation only supports up to one level of implicit pointer dereferencing
zig-pkg/tree_sitter-0.25.0-8heIf4xwAQCcM_rEJFSvWcc0Y6TaXQPw1kFZRWoea4Ne/build.zig:23:8: note: use '.*' to dereference pointer
referenced by:
    runBuild__anon_141352: /nix/store/9zyky24fffkbhnkmjcnrjcl3dmvx6w9x-zig-0.16.0/lib/std/Build.zig:2265:44
    dependencyInner__anon_138706: /nix/store/9zyky24fffkbhnkmjcnrjcl3dmvx6w9x-zig-0.16.0/lib/std/Build.zig:2245:29
    9 reference(s) hidden; use '-freference-trace=11' to see all references
zig-pkg/tree_sitter-0.25.9-Tw2sR_nDCwDWImicW-dekLrHo1GO04pj2MiTtTBBxjlK/build.zig:23:12: error: no field or member function named 'addCSourceFile' in 'Build.Step.Compile'
        lib.addCSourceFile(.{
        ~~~^~~~~~~~~~~~~~~
/nix/store/9zyky24fffkbhnkmjcnrjcl3dmvx6w9x-zig-0.16.0/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const Compile = @This();
^~~~~
zig-pkg/tree_sitter-0.25.9-Tw2sR_nDCwDWImicW-dekLrHo1GO04pj2MiTtTBBxjlK/build.zig:23:12: note: method invocation only supports up to one level of implicit pointer dereferencing
zig-pkg/tree_sitter-0.25.9-Tw2sR_nDCwDWImicW-dekLrHo1GO04pj2MiTtTBBxjlK/build.zig:23:12: note: use '.*' to dereference pointer
zig-pkg/tree_sitter_c-0.24.1-ns1YLwdjQACIi5BEwewiqu6a6Zcl91RWoSWbz0KmxUOj/build.zig:23:8: error: no field or member function named 'addCSourceFile' in 'Build.Step.Compile'
    lib.addCSourceFile(.{
    ~~~^~~~~~~~~~~~~~~
/nix/store/9zyky24fffkbhnkmjcnrjcl3dmvx6w9x-zig-0.16.0/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const Compile = @This();
^~~~~
zig-pkg/tree_sitter_c-0.24.1-ns1YLwdjQACIi5BEwewiqu6a6Zcl91RWoSWbz0KmxUOj/build.zig:23:8: note: method invocation only supports up to one level of implicit pointer dereferencing
zig-pkg/tree_sitter_c-0.24.1-ns1YLwdjQACIi5BEwewiqu6a6Zcl91RWoSWbz0KmxUOj/build.zig:23:8: note: use '.*' to dereference pointer

```
